### PR TITLE
CDS-6 Update styling on <hr>

### PR DESCRIPTION
**Pull request by forkball**
Changlog:
- Update styling on hr to use gradient
- Add link to logo
- Move linebreak class to `global.scss`

### CODE REVIEW

**Review by Liannus — APPROVED** [review]
Looks good, would it make sense to make `linebreak` a global className style since it's being reused though?

**Comment by forkball** [comment]
> 
> 
> Looks good, would it make sense to make `linebreak` a global className style since it's being reused though?

Sounds like a good idea, will do. `index.css` would be the appropriate place for this, imo. What do you think?

**Comment by forkball** [comment]
> 
> 
> > Looks good, would it make sense to make `linebreak` a global className style since it's being reused though?
> 
> Sounds like a good idea, will do. `index.css` would be the appropriate place for this, imo. What do you think?

Nevermind, found the `global.scss`, we should probably get rid of `index.css` then.

**Review by Liannus — APPROVED** [review]
Looks great. 👍

**Pull request merged**
